import "./style.scss";
export declare class BiScrollbar {
    private readonly onUpdate_;
    readonly onUpdate: import("@orange4glace/vs-lib/base/common/event").Event<void>;
    private readonly onChange_;
    readonly onChange: import("@orange4glace/vs-lib/base/common/event").Event<void>;
    pivot: number;
    pivottingOnlyPivotVisible: boolean;
    private scrollSize_;
    get scrollSize(): number;
    private scrollLow_;
    private scrollHigh_;
    private size_;
    private start_;
    get start(): number;
    private end_;
    get end(): number;
    private el_;
    private scrollEl_;
    private handleLEl_;
    private handleREl_;
    private lastMousePos_;
    constructor(parent: HTMLElement);
    setSize(size: number): void;
    setRagne(start: number, end: number): void;
    layout(width: number, height: number): void;
    update(): void;
    private scrollSizeToValueSize;
    private scrollBarPositionToValueRange;
    private handleBarMousedown;
    private handleBarMousemove;
    private handleHandleMousedown;
    private handleHandleMousemove;
}
